[package]
name = "rust_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_demo"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.23"
features = ["extension-module", "abi3-py39"]

[dependencies]
rayon = "1.10"
sha2 = "0.10"
